--- #YAML:1.0
name: CGI-Explorer
version: 2.06
author:
  - Ron Savage <ron@savage.net.au>
abstract: |-
  A class to manage displaying a hash tree of data, for use in CGI scripts
license: artistic
requires:
  Carp: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  CGI::Explorer:
    file: lib/CGI/Explorer.pm
    version: 2.06
generated_by: Module::Build version 0.2611
